spring:
  main:
    banner-mode: "off"
    web-application-type: "none"
  ai:
    mcp:
      server:
        name: "mcp-java-dev-tools"
        version: "0.1.9"
        type: "SYNC"
        stdio: true
        annotation-scanner:
          enabled: true
        capabilities:
          resource: true
          tool: true
          prompt: false
          completion: false

logging:
  level:
    root: INFO
